# Generated by Django 4.2.29 on 2026-04-04 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_sugar', models.DecimalField(decimal_places=2, help_text='Blood sugar level (mg/dL)', max_digits=5)),
                ('meal_description', models.TextField(blank=True, help_text='Brief description of meals')),
                ('insulin_units', models.DecimalField(blank=True, decimal_places=2, help_text='Insulin units taken', max_digits=5, null=True)),
                ('exercised', models.CharField(choices=[('yes', 'Oui / Yes'), ('no', 'Non / No')], default='no', help_text='Did you exercise today?', max_length=3)),
                ('sleep_quality', models.CharField(choices=[('good', 'Bonne / Good'), ('bad', 'Mauvaise / Bad')], default='good', help_text='How was your sleep last night?', max_length=4)),
                ('stressed', models.CharField(choices=[('yes', 'Oui / Yes'), ('no', 'Non / No')], default='no', help_text='Are you feeling stressed today?', max_length=3)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('fr', 'French'), ('ar', 'Arabic')], default='fr', max_length=2)),
                ('summary_text', models.TextField(help_text='AI-generated summary and recommendations')),
                ('logs_analyzed', models.IntegerField(default=0, help_text='Number of log entries analyzed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Summary',
                'verbose_name_plural': 'AI Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
