# Generated by Django 4.2.29 on 2026-04-04 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('gestational', 'Gestationnel / Gestational'), ('prediabetes', 'Prédiabète / Prediabetes')], help_text='Type of diabetes', max_length=20)),
                ('treatment_type', models.CharField(choices=[('insulin_pump', 'Pompe à insuline / Insulin pump'), ('insulin_injections', "Injections d'insuline / Insulin injections"), ('oral_meds', 'Médicaments oraux / Oral medications'), ('diet_exercise', 'Régime et exercice / Diet & exercise only')], help_text='Current treatment approach', max_length=20)),
                ('target_range_low', models.IntegerField(default=70, help_text='Lower target glucose (mg/dL)')),
                ('target_range_high', models.IntegerField(default=180, help_text='Upper target glucose (mg/dL)')),
                ('unit_preference', models.CharField(choices=[('mg_dl', 'mg/dL'), ('mmol_l', 'mmol/L')], default='mg_dl', help_text='Preferred glucose unit', max_length=6)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kg', max_digits=5, null=True)),
                ('height', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
            },
        ),
    ]
