# Generated by Django 4.2.29 on 2026-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='logged_at',
            field=models.DateTimeField(blank=True, help_text='Heure de la mesure (si differente de maintenant)', null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('fasting', 'A jeun'), ('breakfast', 'Petit-dejeuner'), ('lunch', 'Dejeuner'), ('dinner', 'Diner'), ('snack', 'Collation')], default='', help_text='Moment du repas', max_length=10),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='exercised',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non')], default='no', help_text="Exercice aujourd'hui ?", max_length=3),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sleep_quality',
            field=models.CharField(choices=[('good', 'Bonne'), ('bad', 'Mauvaise')], default='good', help_text='Qualite du sommeil', max_length=4),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='stressed',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non')], default='no', help_text='Niveau de stress', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diabetes_type',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('gestational', 'Gestationnel'), ('prediabetes', 'Prediabete')], help_text='Type of diabetes', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='treatment_type',
            field=models.CharField(choices=[('insulin_pump', 'Pompe a insuline'), ('insulin_injections', "Injections d'insuline"), ('oral_meds', 'Medicaments oraux'), ('diet_exercise', 'Regime et exercice')], help_text='Current treatment approach', max_length=20),
        ),
    ]
