# Generated by Django 4.2.29 on 2026-04-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0003_logentry_logged_at_logentry_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], default='female', help_text='Genre', max_length=6),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('fasting', 'À jeun'), ('breakfast', 'Petit-déjeuner'), ('lunch', 'Déjeuner'), ('dinner', 'Dîner'), ('snack', 'Collation')], default='', help_text='Type de repas', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(help_text='Date de naissance'),
        ),
    ]
