# Generated by Django 6.0.3 on 2026-04-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_patientprofile_gender_alter_logentry_meal_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_surprised', models.BooleanField(blank=True, help_text='Was the patient surprised by the insights?', null=True)),
                ('comment', models.TextField(blank=True, default='', help_text="Patient's free-text reaction")),
                ('scenario_id', models.CharField(blank=True, default='', help_text='Which demo scenario was shown (A-E)', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Feedback',
                'verbose_name_plural': 'Demo Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
