# Generated by Django 4.2.29 on 2026-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0005_demofeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='fatigue_level',
            field=models.CharField(choices=[('ok', 'Bien'), ('tired', 'Fatigué(e)')], default='ok', help_text="Niveau de fatigue aujourd'hui", max_length=5),
        ),
        migrations.AddField(
            model_name='logentry',
            name='is_sick',
            field=models.CharField(choices=[('no', 'Non'), ('yes', 'Oui')], default='no', help_text="Malade ou pas bien aujourd'hui", max_length=3),
        ),
    ]
