# Generated by Django 4.2.29 on 2026-04-17 15:03
# Trimmed: AuditLog moved to its own `core` app — see core/migrations/0001.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0006_logentry_fatigue_level_logentry_is_sick'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text="UUID généré côté client (Drift) pour l'idempotence du sync. Même UUID = même entrée.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='daily_wellness',
            field=models.JSONField(blank=True, default=dict, help_text="Blob structuré regroupant fatigue/is_sick/stressed/sleep_quality dans le flux futur. Les colonnes historiques restent la source de vérité tant que la migration n'est pas complète."),
        ),
        migrations.AddField(
            model_name='logentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuel'), ('voice', 'Vocal'), ('cgm', 'CGM'), ('import', 'Import'), ('demo', 'Démo')], default='manual', help_text="Provenance de l'entrée — manuel, vocal, CGM, import ou démo.", max_length=16),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Firebase Auth UID once the patient migrates from legacy login.', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('ar-MA', 'Darija')], default='fr', help_text='UI language preference (Flutter + future Django i18n).', max_length=8),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='premium_valid_until',
            field=models.DateTimeField(blank=True, help_text='End of paid Premium access (Payzone/M2T/Cash Plus).', null=True),
        ),
    ]
