# Generated by Django 6.0.4 on 2026-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0007_amina_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='meal_items',
            field=models.JSONField(blank=True, default=list, help_text='IDs structurés des plats sélectionnés via le dictionnaire culinaire.'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='meal_description',
            field=models.TextField(blank=True, help_text='Texte libre décrivant le repas'),
        ),
    ]
