# Generated by Django 6.0.4 on 2026-04-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0008_logentry_meal_items_alter_logentry_meal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('fasting', 'À jeun'), ('breakfast', 'Petit-déjeuner'), ('lunch', 'Déjeuner'), ('snack', 'Collation'), ('dinner', 'Dîner'), ('iftar', 'Iftar'), ('suhoor', 'Suhoor'), ('other', 'Autre')], default='', help_text='Type de repas', max_length=10),
        ),
    ]
