# Generated by Django 6.0.3 on 2026-04-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0009_alter_logentry_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'IAmina')], help_text='Rôle dans la conversation (user/assistant)', max_length=10)),
                ('message', models.TextField(help_text='Contenu du message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt_hash', models.CharField(blank=True, help_text='Hash SHA-256 du prompt template utilisé', max_length=64, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Chat IA',
                'verbose_name_plural': 'Messages Chat IA',
                'ordering': ['created_at'],
            },
        ),
    ]
