# Generated by Django 6.0.3 on 2026-05-23 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0011_iamina_memory_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='ai_consent_given_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the patient explicitly consented to AI analysis. NULL = no consent.', null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('consent_given', 'Consentement IA accordé'), ('consent_withdrawn', 'Consentement IA retiré'), ('account_deleted', 'Compte supprimé (RGPD)'), ('data_export', 'Export données (RGPD)'), ('login', 'Connexion'), ('password_change', 'Changement de mot de passe')], db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
