# Generated by Django 6.0.3 on 2026-05-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0012_rgpd_audit_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('ar-MA', 'Darija (dialecte marocain)'), ('ar', 'Arabe classique (Fusha)')], default='ar-MA', help_text='UI language preference (Flutter + future Django i18n).', max_length=8),
        ),
    ]
