# Generated by Django 6.0.3 on 2026-05-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0014_remove_daily_wellness_blood_sugar_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('lab_report', 'Bilan biologique'), ('cgm_export', 'Export CGM'), ('glucose_log', 'Carnet glycémique'), ('prescription', 'Ordonnance'), ('medical_report', 'Compte-rendu médical'), ('unknown', 'Inconnu')], default='unknown', max_length=32)),
                ('source_format', models.CharField(choices=[('pdf', 'PDF'), ('pdf_scanned', 'PDF scanné'), ('image', 'Image / Photo'), ('excel', 'Excel / CSV'), ('docx', 'Document Word'), ('unknown', 'Inconnu')], default='unknown', max_length=32)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('hba1c_pct', models.FloatField(blank=True, help_text='HbA1c %', null=True)),
                ('fasting_glucose_mgdl', models.FloatField(blank=True, help_text='Glucose à jeun mg/dL', null=True)),
                ('total_cholesterol_mgdl', models.FloatField(blank=True, null=True)),
                ('hdl_mgdl', models.FloatField(blank=True, null=True)),
                ('ldl_mgdl', models.FloatField(blank=True, null=True)),
                ('triglycerides_mgdl', models.FloatField(blank=True, null=True)),
                ('creatinine_umol', models.FloatField(blank=True, null=True)),
                ('glucose_readings_imported', models.IntegerField(default=0, help_text='LogEntry rows created from this document')),
                ('import_batch_id', models.CharField(blank=True, default='', help_text='Links LogEntry rows to this report', max_length=64)),
                ('confidence', models.FloatField(default=0.0, help_text='0.0–1.0 extraction confidence')),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='', help_text='Full extracted text for audit trail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
