# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0023_diabetesprofile_ramadan_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalObservationState',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('observation_key', models.CharField(max_length=64)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('context', 'Recorded context association'),
                            ('meal', 'Recorded post-meal association'),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    'truth_kind',
                    models.CharField(
                        default='deterministic_derivation',
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active observation'),
                            ('inactive', 'Inactive observation'),
                        ],
                        default='active',
                        max_length=16,
                    ),
                ),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurrence_count', models.PositiveIntegerField(default=1)),
                (
                    'evidence_strength',
                    models.CharField(
                        choices=[
                            ('limited', 'Limited repeatability'),
                            ('moderate', 'Moderate repeatability'),
                            ('strong', 'Strong repeatability'),
                        ],
                        max_length=16,
                    ),
                ),
                ('previous_evidence_strength', models.CharField(blank=True, default='', max_length=16)),
                (
                    'evidence_strength_trend',
                    models.CharField(
                        choices=[
                            ('initial', 'Initial evidence grade'),
                            ('stable', 'Stable evidence grade'),
                            ('strengthening', 'Strengthening repeatability'),
                            ('weakening', 'Weakening repeatability'),
                        ],
                        default='initial',
                        max_length=16,
                    ),
                ),
                ('observations', models.PositiveIntegerField()),
                ('distinct_days', models.PositiveIntegerField()),
                ('observation_median_glucose_mg_dl', models.FloatField()),
                ('window_median_glucose_mg_dl', models.FloatField()),
                ('baseline_delta_mg_dl', models.FloatField()),
                ('previous_baseline_delta_mg_dl', models.FloatField(blank=True, null=True)),
                ('baseline_delta_change_mg_dl', models.FloatField(blank=True, null=True)),
                ('evidence_window_days', models.PositiveSmallIntegerField(default=90)),
                ('evidence_id', models.CharField(max_length=96)),
                ('producer', models.CharField(max_length=96)),
                ('context_modifiers', models.JSONField(default=dict)),
                ('last_evidence_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='clinical_observation_states',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('patient_id', 'observation_key'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('patient', 'observation_key'),
                        name='uniq_patient_clinical_observation_key',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('truth_kind', 'deterministic_derivation')),
                        name='clinical_obs_truth_deterministic',
                    ),
                ],
            },
        ),
    ]
