# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0024_clinicalobservationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalInsightState',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('observation_key', models.CharField(max_length=64)),
                (
                    'truth_kind',
                    models.CharField(
                        default='deterministic_derivation',
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    'producer',
                    models.CharField(
                        default='diabetes.proactive_attention.v1',
                        editable=False,
                        max_length=96,
                    ),
                ),
                (
                    'source_producer',
                    models.CharField(
                        default='diabetes.personal_response.v1',
                        editable=False,
                        max_length=96,
                    ),
                ),
                (
                    'source_evidence_id',
                    models.CharField(
                        default='rule.personal-response.repetition.v1',
                        editable=False,
                        max_length=96,
                    ),
                ),
                (
                    'lifecycle_state',
                    models.CharField(
                        choices=[
                            ('new', 'New'),
                            ('monitoring', 'Monitoring'),
                            ('persisting', 'Persisting'),
                            ('improving', 'Improving toward recorded baseline'),
                            ('resolved', 'Resolved from proactive attention'),
                            ('escalated', 'Escalated by governed criterion'),
                        ],
                        default='new',
                        max_length=16,
                    ),
                ),
                (
                    'allowed_next_step',
                    models.CharField(
                        choices=[
                            ('monitor', 'Monitor'),
                            ('collect_missing_data', 'Collect missing data'),
                        ],
                        default='monitor',
                        max_length=32,
                    ),
                ),
                ('source_status_snapshot', models.CharField(blank=True, default='', max_length=16)),
                ('recurrence_count_snapshot', models.PositiveIntegerField(default=0)),
                ('evidence_strength_snapshot', models.CharField(blank=True, default='', max_length=16)),
                ('baseline_delta_snapshot_mg_dl', models.FloatField(blank=True, null=True)),
                ('observations_snapshot', models.PositiveIntegerField(default=0)),
                ('distinct_days_snapshot', models.PositiveIntegerField(default=0)),
                ('dataset_eligible_snapshot', models.BooleanField(default=False)),
                ('last_material_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('last_decision_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('last_surfaced_decision_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('pending_reason_codes', models.JSONField(default=list)),
                ('first_surfaced_at', models.DateTimeField(blank=True, null=True)),
                ('last_surfaced_at', models.DateTimeField(blank=True, null=True)),
                ('surface_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'observation',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='proactive_insight_state',
                        to='diabetes.clinicalobservationstate',
                    ),
                ),
            ],
            options={
                'ordering': ('observation__patient_id', 'observation_key'),
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('truth_kind', 'deterministic_derivation')),
                        name='clinical_insight_truth_deterministic',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('producer', 'diabetes.proactive_attention.v1')),
                        name='clinical_insight_producer_approved',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('source_producer', 'diabetes.personal_response.v1')),
                        name='clinical_insight_source_producer_approved',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('source_evidence_id', 'rule.personal-response.repetition.v1')),
                        name='clinical_insight_source_evidence_approved',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('lifecycle_state', 'escalated'), _negated=True),
                        name='clinical_insight_no_unruled_escalation',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(('allowed_next_step__in', ('monitor', 'collect_missing_data'))),
                        name='clinical_insight_safe_action_only',
                    ),
                ],
            },
        ),
    ]
