# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diabetes", "0024_clinicalobservationstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProactiveInsightState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("monitoring", "Monitoring"),
                            ("persisting", "Persisting"),
                            ("improving", "Improving"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "clinical_relevance",
                    models.CharField(
                        choices=[
                            ("observational", "Observational"),
                            ("review_worthy", "Review worthy"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "action_class",
                    models.CharField(
                        choices=[
                            ("MONITOR", "Monitor"),
                            (
                                "PREPARE_CLINICIAN_DISCUSSION",
                                "Prepare clinician discussion",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "escalation_class",
                    models.CharField(
                        default="none",
                        editable=False,
                        max_length=24,
                    ),
                ),
                ("last_observation_fingerprint", models.CharField(max_length=64)),
                ("current_signature", models.CharField(max_length=64)),
                (
                    "last_delivered_signature",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_surfaced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proactive_insight",
                        to="diabetes.clinicalobservationstate",
                    ),
                ),
            ],
            options={
                "ordering": ("observation_id",),
                "indexes": [
                    models.Index(
                        fields=["last_surfaced_at"],
                        name="proactive_last_surface_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            state__in=(
                                "new",
                                "monitoring",
                                "persisting",
                                "improving",
                                "resolved",
                            )
                        ),
                        name="proactive_personal_response_state_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            clinical_relevance__in=(
                                "observational",
                                "review_worthy",
                            )
                        ),
                        name="proactive_personal_response_relevance_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            action_class__in=(
                                "MONITOR",
                                "PREPARE_CLINICIAN_DISCUSSION",
                            )
                        ),
                        name="proactive_personal_response_action_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(escalation_class="none"),
                        name="proactive_personal_response_no_escalation",
                    ),
                ],
            },
        ),
    ]
