# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diabetes", "0025_proactiveinsightstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanionReviewAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="companion.explicit-review.v1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "snapshot_version",
                    models.CharField(
                        default="clinical-observation-snapshot.v1",
                        editable=False,
                        max_length=64,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_review_anchors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["patient", "-captured_at"],
                        name="comp_review_patient_latest_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(source="companion.explicit-review.v1"),
                        name="comp_review_anchor_source_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            snapshot_version="clinical-observation-snapshot.v1"
                        ),
                        name="comp_review_anchor_version_safe",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanionReviewObservationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_key", models.CharField(max_length=64)),
                (
                    "truth_kind",
                    models.CharField(
                        default="deterministic_derivation",
                        editable=False,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active observation"),
                            ("inactive", "Inactive observation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("status_changed_at", models.DateTimeField()),
                ("last_refreshed_at", models.DateTimeField()),
                ("recurrence_count", models.PositiveIntegerField()),
                (
                    "evidence_strength",
                    models.CharField(
                        choices=[
                            ("limited", "Limited repeatability"),
                            ("moderate", "Moderate repeatability"),
                            ("strong", "Strong repeatability"),
                        ],
                        max_length=16,
                    ),
                ),
                ("baseline_delta_mg_dl", models.FloatField()),
                ("observation_median_glucose_mg_dl", models.FloatField()),
                ("window_median_glucose_mg_dl", models.FloatField()),
                ("evidence_window_days", models.PositiveSmallIntegerField()),
                ("evidence_id", models.CharField(max_length=96)),
                ("producer", models.CharField(max_length=96)),
                ("evidence_fingerprint", models.CharField(max_length=64)),
                (
                    "anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_snapshots",
                        to="diabetes.companionreviewanchor",
                    ),
                ),
            ],
            options={
                "ordering": ("anchor_id", "observation_key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anchor", "observation_key"),
                        name="uniq_comp_review_anchor_observation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(truth_kind="deterministic_derivation"),
                        name="comp_review_snapshot_truth_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(producer="diabetes.personal_response.v1"),
                        name="comp_review_snapshot_producer_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            evidence_id="rule.personal-response.repetition.v1"
                        ),
                        name="comp_review_snapshot_evidence_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(status__in=("active", "inactive")),
                        name="comp_review_snapshot_status_safe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            evidence_strength__in=("limited", "moderate", "strong")
                        ),
                        name="comp_review_snapshot_density_safe",
                    ),
                ],
            },
        ),
    ]
