"""Vercel-only CSRF origin policy for the IAMINA frontend.

Keep Django's normal CSRF token enforcement. This middleware only extends
origin verification to IAMINA frontend deployment hostnames generated by the
known Vercel account; unrelated ``*.vercel.app`` origins remain untrusted.
"""
from __future__ import annotations

import re

from django.middleware.csrf import CsrfViewMiddleware

IAMINA_FRONTEND_STABLE_ORIGIN = "https://iamina-review.vercel.app"
IAMINA_FRONTEND_DEPLOYMENT_ORIGIN_RE = re.compile(
    r"^https://iamina-review-[a-z0-9-]+-achraf-benmoussa-s-projects\.vercel\.app$",
    re.IGNORECASE,
)


def is_iamina_frontend_origin(origin: str) -> bool:
    """Return True only for the stable alias or known IAMINA deployment hosts."""
    normalized = origin.strip().lower()
    return normalized == IAMINA_FRONTEND_STABLE_ORIGIN or bool(
        IAMINA_FRONTEND_DEPLOYMENT_ORIGIN_RE.fullmatch(normalized)
    )


class IaminaVercelCsrfViewMiddleware(CsrfViewMiddleware):
    """Preserve Django CSRF checks while accepting IAMINA Vercel deployments."""

    def _origin_verified(self, request):
        if super()._origin_verified(request):
            return True
        return is_iamina_frontend_origin(request.META.get("HTTP_ORIGIN", ""))
