from pathlib import Path

root = Path(__file__).resolve().parents[1]
frontend = root / 'frontend'

# Post-process implementation generated by ux11_apply.py.
dash_path = frontend / 'lib/features/dashboard/dashboard_convergent_screen.dart'
dash = dash_path.read_text()
dash = dash.replace(
    "child: InkWell(\n            onTap: () => GoRouter.of(context).go('/importer'),",
    "child: InkWell(\n            key: const ValueKey('dashboard-import-action'),\n            onTap: () => GoRouter.of(context).go('/importer'),",
    1,
)
dash_path.write_text(dash)

for relative in [
    'lib/features/medications/medication_screen.dart',
    'lib/features/reminders/reminders_screen.dart',
]:
    path = frontend / relative
    text = path.read_text()
    text = text.replace(
        'padding: const EdgeInsets.fromLTRB(20, 16, 20, 40),',
        'padding: const EdgeInsetsDirectional.fromSTEB(20, 16, 20, 40),',
    )
    text = text.replace(
        'if (date == null || !mounted) return;',
        'if (date == null || !context.mounted) return;',
    )
    text = text.replace(
        'if (time == null || !mounted) return;',
        'if (time == null || !context.mounted) return;',
    )
    path.write_text(text)

# UX-11 mobile nav contract: four destinations + central add.
(frontend / 'test/p0_ux_8_mobile_navigation_test.dart').write_text(r'''import 'package:amina/features/navigation/main_shell.dart';
import 'package:amina/l10n/app_localizations.dart';
import 'package:amina/services/api_client.dart';
import 'package:amina/services/modules_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  Future<GoRouter> pumpNavigation(
    WidgetTester tester, {
    required Locale locale,
  }) async {
    tester.view.physicalSize = const Size(390, 844);
    tester.view.devicePixelRatio = 1;

    final api = ApiClient(baseUrl: 'http://127.0.0.1:1');
    final modules = ModulesProvider(api);
    final router = GoRouter(
      initialLocation: '/dashboard',
      routes: [
        GoRoute(
          path: '/ajouter',
          builder: (_, __) => const Scaffold(body: Text('route:/ajouter')),
        ),
        ShellRoute(
          builder: (_, __, child) => MainShell(child: child),
          routes: [
            for (final route in const [
              '/dashboard',
              '/summary',
              '/journal',
              '/importer',
              '/profile',
            ])
              GoRoute(
                path: route,
                builder: (_, __) =>
                    Scaffold(body: Center(child: Text('route:$route'))),
              ),
          ],
        ),
      ],
    );

    await tester.pumpWidget(
      ChangeNotifierProvider<ModulesProvider>.value(
        value: modules,
        child: MaterialApp.router(
          routerConfig: router,
          locale: locale,
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          supportedLocales: AppLocalizations.supportedLocales,
        ),
      ),
    );
    await tester.pumpAndSettle();
    return router;
  }

  Finder destination(String route) => find.byKey(ValueKey('mobile-nav-$route'));
  Finder get addDestination => find.byKey(const ValueKey('mobile-nav-add'));

  void expectApprovedDestinations() {
    for (final route in const [
      '/dashboard',
      '/journal',
      '/summary',
      '/profile',
    ]) {
      expect(destination(route), findsOneWidget);
    }
    expect(destination('/importer'), findsNothing);
    expect(addDestination, findsOneWidget);
  }

  void expectTouchTargets(WidgetTester tester) {
    for (final route in const [
      '/dashboard',
      '/journal',
      '/summary',
      '/profile',
    ]) {
      final size = tester.getSize(destination(route));
      expect(size.width, greaterThanOrEqualTo(48));
      expect(size.height, greaterThanOrEqualTo(48));
    }
    final addSize = tester.getSize(addDestination);
    expect(addSize.width, greaterThanOrEqualTo(48));
    expect(addSize.height, greaterThanOrEqualTo(48));
  }

  Finder semanticsContaining(String label) =>
      find.bySemanticsLabel(RegExp(RegExp.escape(label)));

  testWidgets('390px French navigation matches approved UX-11 semantics', (
    tester,
  ) async {
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
    final semantics = tester.ensureSemantics();
    final router = await pumpNavigation(tester, locale: const Locale('fr'));
    addTearDown(router.dispose);

    expectApprovedDestinations();
    expect(
      Directionality.of(tester.element(destination('/dashboard'))),
      TextDirection.ltr,
    );
    for (final label in const ['Accueil', 'Mesures', 'Rapports', 'Profil']) {
      expect(find.text(label), findsOneWidget);
      expect(semanticsContaining(label), findsWidgets);
    }
    expectTouchTargets(tester);

    await tester.tap(destination('/journal'));
    await tester.pumpAndSettle();
    expect(router.routeInformationProvider.value.uri.path, '/journal');
    expectApprovedDestinations();

    await tester.tap(addDestination);
    await tester.pumpAndSettle();
    expect(router.routeInformationProvider.value.uri.path, '/ajouter');
    expect(tester.takeException(), isNull);
    semantics.dispose();
  });

  testWidgets('390px Arabic navigation is RTL and route-aware', (tester) async {
    addTearDown(tester.view.resetPhysicalSize);
    addTearDown(tester.view.resetDevicePixelRatio);
    final semantics = tester.ensureSemantics();
    final router = await pumpNavigation(tester, locale: const Locale('ar'));
    addTearDown(router.dispose);

    expectApprovedDestinations();
    expect(
      Directionality.of(tester.element(destination('/dashboard'))),
      TextDirection.rtl,
    );
    for (final label in const ['الرئيسية', 'القياسات', 'التقارير', 'الملف الشخصي']) {
      expect(find.text(label), findsOneWidget);
      expect(semanticsContaining(label), findsWidgets);
    }
    expectTouchTargets(tester);

    await tester.tap(destination('/summary'));
    await tester.pumpAndSettle();
    expect(router.routeInformationProvider.value.uri.path, '/summary');
    expectApprovedDestinations();
    expect(tester.takeException(), isNull);
    semantics.dispose();
  });
}
''')

# Navigation remains real while Import is deliberately reached outside bottom nav.
real_actions = frontend / 'test/p0_real_actions_contract_test.dart'
text = real_actions.read_text()
old = r'''  test('mobile navigation derives every destination including Importer', () {
    final module = _read('lib/modules/diabetes_module.dart');
    final shell = _read('lib/features/navigation/main_shell.dart');

    expect(module, contains("route: '/importer'"));
    expect(
      shell,
      contains('for (var index = 0; index < entries.length; index++)'),
    );
    expect(shell, contains('_GlassNavDestination('));
    expect(shell, contains('entry: entries[index]'));
    expect(shell, contains("ValueKey('mobile-nav-\${entry.route}')"));
    expect(shell, contains('GoRouter.of(context).go(entries[index].route)'));
  });'''
new = r'''  test('mobile navigation exposes approved destinations while Import stays reachable', () {
    final module = _read('lib/modules/diabetes_module.dart');
    final shell = _read('lib/features/navigation/main_shell.dart');
    final dashboard = _read('lib/features/dashboard/dashboard_convergent_screen.dart');

    expect(module, contains("route: '/importer'"));
    expect(shell, contains("entry.route != '/importer'"));
    expect(shell, contains('_GlassNavDestination('));
    expect(shell, contains('entry: mobileEntries[index]'));
    expect(shell, contains("ValueKey('mobile-nav-\${entry.route}')"));
    expect(shell, contains('GoRouter.of(context).go(mobileEntries[index].route)'));
    expect(shell, contains("GoRouter.of(context).go('/ajouter')"));
    expect(dashboard, contains("ValueKey('dashboard-import-action')"));
    expect(dashboard, contains("GoRouter.of(context).go('/importer')"));
  });'''
assert old in text
real_actions.write_text(text.replace(old, new, 1))

# Glass navigation contract follows the mobileEntries projection.
glass = frontend / 'test/ux_5_glass_mobile_nav_contract_test.dart'
text = glass.read_text()
text = text.replace(
    "expect(source, contains('GoRouter.of(context).go(entries[index].route)'));",
    "expect(source, contains('GoRouter.of(context).go(mobileEntries[index].route)'));\n      expect(source, contains(\"entry.route != '/importer'\"));\n      expect(source, contains(\"ValueKey('mobile-nav-add')\"));",
)
glass.write_text(text)

# Importer is still reachable on mobile from the truthful dashboard header action.
mobile_import = frontend / 'test/p0_mobile_import_navigation_test.dart'
text = mobile_import.read_text()
text = text.replace(
    "import 'package:amina/features/documents/document_import_screen.dart';",
    "import 'package:amina/features/dashboard/dashboard_convergent_screen.dart';\nimport 'package:amina/features/documents/document_import_screen.dart';",
    1,
)
text = text.replace(
    "builder: (_, __) => const Scaffold(\n                  body: Center(child: Text('Dashboard test marker')),\n                ),",
    "builder: (_, __) => const DashboardConvergentScreen(),",
    1,
)
old = r'''      final importerDestination = find.byKey(
        const ValueKey('mobile-nav-/importer'),
      );
      expect(importerDestination, findsOneWidget);
      expect(tester.takeException(), isNull);

      await tester.tap(importerDestination);'''
new = r'''      final importerAction = find.byKey(
        const ValueKey('dashboard-import-action'),
      );
      expect(importerAction, findsOneWidget);
      expect(find.byKey(const ValueKey('mobile-nav-/importer')), findsNothing);
      expect(tester.takeException(), isNull);

      await tester.tap(importerAction);'''
assert old in text
mobile_import.write_text(text.replace(old, new, 1))

# Importer/Pulper test should assert semantics, not formatter line wrapping.
import_contract = frontend / 'test/p0_ux_10_importer_document_entry_contract_test.dart'
text = import_contract.read_text()
text = text.replace(
    'expect(module, contains("ModuleFullScreenRoute(path: \'/pulper\'"));',
    'expect(module, contains("path: \'/pulper\'"));\n    expect(module, contains("DocumentImportScreen"));',
)
import_contract.write_text(text)

# Register new screens in RTL certification.
rtl = frontend / 'test/rtl_screen_contract_test.dart'
text = rtl.read_text()
marker = r'''  _RtlScreenEntry(
    route: '/pulper',
    widget: 'DocumentImportScreen',
    source: 'lib/features/documents/document_import_screen.dart',
  ),'''
insert = marker + r'''
  _RtlScreenEntry(
    route: '/medications',
    widget: 'MedicationScreen',
    source: 'lib/features/medications/medication_screen.dart',
  ),
  _RtlScreenEntry(
    route: '/reminders',
    widget: 'RemindersScreen',
    source: 'lib/features/reminders/reminders_screen.dart',
  ),'''
assert marker in text
rtl.write_text(text.replace(marker, insert, 1))

# Latest Drift schema is v10. Also certify that the new v10 tables exist after legacy upgrades.
for rel in [
    'test/data/drift/glycemic_context_migration_test.dart',
    'test/data/drift/meal_items_migration_test.dart',
    'test/data/drift/meal_portions_migration_test.dart',
    'test/data/drift/ramadan_period_migration_test.dart',
]:
    path = frontend / rel
    text = path.read_text().replace("expect(version.data['user_version'], 9);", "expect(version.data['user_version'], 10);")
    probe = """        final v10Tables = await db.customSelect(\n          \"SELECT name FROM sqlite_master WHERE type = 'table' AND name IN ('medication_events', 'reminders')\",\n        ).get();\n        expect(v10Tables.map((row) => row.data['name']).toSet(), {'medication_events', 'reminders'});\n"""
    anchor = "        expect(version.data['user_version'], 10);"
    if anchor in text and 'final v10Tables' not in text:
        text = text.replace(anchor, anchor + '\n' + probe, 1)
    path.write_text(text)
