"""
Tests — LibreLink/LibreView CSV parser.

Run: python manage.py test diabetes.tests.test_librelink_parser --verbosity=2
"""
import unittest

from diabetes.services.import_csv.librelink_parser import (
    LibreLinkParseResult,
    LibreReading,
    parse_librelink_csv,
)

# ── Fixtures ──────────────────────────────────────────────────────────────────

# Real-world LibreView FR export (truncated)
LIBREVIEW_DETAILED_FR = """\
"Patient name","Smith, John","Patient ID","00000000-0000-0000-0000-000000000000"
"Generated on","12-05-2026 10:00","Generated by","LibreView Web"
"Device","Serial Number","Horodatage de l'appareil","Record Type","Glucose historique mg/dL","Glucose lu mg/dL","Strip Glucose mg/dL"
"LibreView","12345","11-05-2026 08:30","0","150","",""
"LibreView","12345","11-05-2026 08:45","0","162","",""
"LibreView","12345","11-05-2026 09:00","1","","178",""
"LibreView","12345","11-05-2026 09:15","0","185","",""
"LibreView","12345","11-05-2026 09:30","0","140","",""
"""

SIMPLE_CSV_MGDL = """\
Device Timestamp,Glucose Value,Glucose Unit
11-05-2026 08:00,120,mg/dL
11-05-2026 09:00,145,mg/dL
11-05-2026 10:00,168,mg/dL
"""

SIMPLE_CSV_MMOL = """\
Device Timestamp,Glucose Value,Glucose Unit
11-05-2026 08:00,7.5,mmol/L
11-05-2026 09:00,9.0,mmol/L
"""

OUT_OF_RANGE = """\
Device Timestamp,Glucose Value,Glucose Unit
11-05-2026 08:00,150,mg/dL
11-05-2026 09:00,9999,mg/dL
11-05-2026 10:00,5,mg/dL
11-05-2026 11:00,200,mg/dL
"""


# ── FR format detection ───────────────────────────────────────────────────────

class TestLibreLinkDetailedFR(unittest.TestCase):

    def test_detects_libreview_fr_format(self):
        r = parse_librelink_csv(LIBREVIEW_DETAILED_FR)
        self.assertEqual(r.detected_format, "librelink_detailed")

    def test_parses_correct_reading_count(self):
        r = parse_librelink_csv(LIBREVIEW_DETAILED_FR)
        self.assertEqual(len(r.readings), 5)

    def test_first_glucose_value(self):
        r = parse_librelink_csv(LIBREVIEW_DETAILED_FR)
        self.assertEqual(r.readings[0].glucose_mgdl, 150.0)

    def test_timestamps_parsed_correctly(self):
        r = parse_librelink_csv(LIBREVIEW_DETAILED_FR)
        first = r.readings[0].timestamp
        self.assertEqual(first.year, 2026)
        self.assertEqual(first.month, 5)
        self.assertEqual(first.day, 11)
        self.assertEqual(first.hour, 8)
        self.assertEqual(first.minute, 30)


# ── EN format detection ───────────────────────────────────────────────────────

class TestSimpleCsvEN(unittest.TestCase):

    def test_detects_simple_format(self):
        r = parse_librelink_csv(SIMPLE_CSV_MGDL)
        self.assertEqual(r.detected_format, "simple")

    def test_simple_mgdl_passthrough(self):
        r = parse_librelink_csv(SIMPLE_CSV_MGDL)
        self.assertEqual(len(r.readings), 3)
        self.assertEqual([rd.glucose_mgdl for rd in r.readings], [120.0, 145.0, 168.0])


# ── mmol/L conversion ─────────────────────────────────────────────────────────

class TestMmolConversion(unittest.TestCase):

    def test_mmol_converted_to_mgdl(self):
        r = parse_librelink_csv(SIMPLE_CSV_MMOL)
        self.assertEqual(len(r.readings), 2)
        # 7.5 mmol/L × 18 = 135 mg/dL
        self.assertAlmostEqual(r.readings[0].glucose_mgdl, 135.0, places=0)

    def test_mmol_unit_detected(self):
        r = parse_librelink_csv(SIMPLE_CSV_MMOL)
        self.assertEqual(r.detected_unit, "mmol/L")


# ── Out-of-range rejection ────────────────────────────────────────────────────

class TestOutOfRangeRejection(unittest.TestCase):

    def test_out_of_range_values_rejected(self):
        r = parse_librelink_csv(OUT_OF_RANGE)
        # 150 and 200 are valid; 9999 and 5 are out of physiological range
        self.assertEqual(len(r.readings), 2)
        self.assertEqual(r.rejected_values, 2)

    def test_valid_values_preserved(self):
        r = parse_librelink_csv(OUT_OF_RANGE)
        self.assertEqual([rd.glucose_mgdl for rd in r.readings], [150.0, 200.0])

    def test_empty_csv_returns_error(self):
        r = parse_librelink_csv("")
        self.assertEqual(r.error, "empty_csv")
        self.assertEqual(r.total_parsed, 0)

    def test_garbage_csv_returns_error(self):
        r = parse_librelink_csv("hello\nworld\nfoobar")
        self.assertIn(r.error, ("no_header_found", "unknown_format"))

    def test_unknown_format_returns_error(self):
        r = parse_librelink_csv("Foo,Bar,Baz,Qux\n1,2,3,4\n5,6,7,8\n")
        self.assertIsNotNone(r.error)


# ── Duplicate UUID idempotency ────────────────────────────────────────────────

class TestDuplicateUuidIdempotency(unittest.TestCase):
    """
    Parsing the same CSV twice must produce identical LibreReading objects so
    that the caller can use the deterministic UUID to skip duplicates.
    """

    def test_same_csv_produces_identical_readings(self):
        r1 = parse_librelink_csv(SIMPLE_CSV_MGDL)
        r2 = parse_librelink_csv(SIMPLE_CSV_MGDL)
        self.assertEqual(len(r1.readings), len(r2.readings))
        for a, b in zip(r1.readings, r2.readings):
            self.assertEqual(a.timestamp, b.timestamp)
            self.assertEqual(a.glucose_mgdl, b.glucose_mgdl)
            self.assertEqual(a.record_type, b.record_type)

    def test_deterministic_uuid_helper(self):
        """The UUID derived from the same inputs must be identical across calls."""
        import hashlib
        import uuid
        def make_uuid(patient_id, ts, glucose):
            seed = f"librelink:{patient_id}:{ts}:{glucose:.1f}"
            digest = hashlib.sha256(seed.encode()).digest()
            return str(uuid.UUID(bytes=digest[:16]))

        u1 = make_uuid(42, "2026-05-11T08:30:00", 150.0)
        u2 = make_uuid(42, "2026-05-11T08:30:00", 150.0)
        self.assertEqual(u1, u2)

    def test_different_glucose_produces_different_uuid(self):
        import hashlib
        import uuid
        def make_uuid(patient_id, ts, glucose):
            seed = f"librelink:{patient_id}:{ts}:{glucose:.1f}"
            digest = hashlib.sha256(seed.encode()).digest()
            return str(uuid.UUID(bytes=digest[:16]))

        u1 = make_uuid(42, "2026-05-11T08:30:00", 150.0)
        u2 = make_uuid(42, "2026-05-11T08:30:00", 151.0)
        self.assertNotEqual(u1, u2)


# ── Malformed rows skipped ────────────────────────────────────────────────────

class TestMalformedRowsSkipped(unittest.TestCase):

    def test_rows_with_bad_timestamp_skipped(self):
        csv_with_bad_ts = (
            "Device Timestamp,Glucose Value,Glucose Unit\n"
            "NOT_A_DATE,120,mg/dL\n"
            "11-05-2026 08:00,150,mg/dL\n"
        )
        r = parse_librelink_csv(csv_with_bad_ts)
        # Only the valid row should parse
        self.assertEqual(len(r.readings), 1)
        self.assertEqual(r.skipped_rows, 1)

    def test_empty_rows_skipped_without_crash(self):
        csv_with_empties = (
            "Device Timestamp,Glucose Value,Glucose Unit\n"
            "\n"
            "11-05-2026 08:00,120,mg/dL\n"
            "   \n"
            "11-05-2026 09:00,145,mg/dL\n"
        )
        r = parse_librelink_csv(csv_with_empties)
        self.assertEqual(len(r.readings), 2)

    def test_record_type_priority_historic_over_scan(self):
        """When both historic and scan present in same row, historic wins."""
        r = parse_librelink_csv(LIBREVIEW_DETAILED_FR)
        # Row 0: historic=150, scan="" → should be "historic"
        self.assertEqual(r.readings[0].record_type, "historic")
        # Row 2: historic="", scan=178 → should be "scan"
        self.assertEqual(r.readings[2].record_type, "scan")


if __name__ == "__main__":
    unittest.main(verbosity=2)
