// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QHQrXSpQT1gjGA6I20cYdCsVG-BNxGI',
    appId: '1:231591358771:web:f89c2104b07d47b4eb4e46',
    messagingSenderId: '231591358771',
    projectId: 'iamina',
    authDomain: 'iamina.firebaseapp.com',
    storageBucket: 'iamina.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFhSk25FfcTSbyZInXqeCbOQm0eZVldm0',
    appId: '1:231591358771:ios:3fb485cb6f134a5aeb4e46',
    messagingSenderId: '231591358771',
    projectId: 'iamina',
    storageBucket: 'iamina.firebasestorage.app',
    iosClientId: '231591358771-015unol3l0mc03b9iqu6uqrs7j1n0iqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.amina',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFhSk25FfcTSbyZInXqeCbOQm0eZVldm0',
    appId: '1:231591358771:ios:9caa25b5126781efeb4e46',
    messagingSenderId: '231591358771',
    projectId: 'iamina',
    storageBucket: 'iamina.firebasestorage.app',
    iosClientId: '231591358771-s8ci3nf2uvpk73tvgavp4b0u2s2f8kcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.amina',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbC1HJ4AlIsN5vB9E5eLSgF4jnhPGqHuk',
    appId: '1:231591358771:android:5433a266b7a967cfeb4e46',
    messagingSenderId: '231591358771',
    projectId: 'iamina',
    storageBucket: 'iamina.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3QHQrXSpQT1gjGA6I20cYdCsVG-BNxGI',
    appId: '1:231591358771:web:faa77383e484e957eb4e46',
    messagingSenderId: '231591358771',
    projectId: 'iamina',
    authDomain: 'iamina.firebaseapp.com',
    storageBucket: 'iamina.firebasestorage.app',
  );

}