# Generated by Django 4.2.29 on 2026-04-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export')], db_index=True, help_text="Type d'action journalisée.", max_length=64)),
                ('resource_type', models.CharField(help_text='Modèle Django concerné (ex. LogEntry, PatientProfile).', max_length=64)),
                ('resource_id', models.CharField(blank=True, help_text='Identifiant de la ressource visée (primary key ou UUID).', max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexte complémentaire ; jamais de PHI en clair.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('actor', models.ForeignKey(blank=True, help_text="Utilisateur à l'origine de l'action (null si supprimé a posteriori).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
