# Generated by Django 6.0.3 on 2026-06-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_observabilityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_snapshot', models.IntegerField(help_text='PK of the deleted Django User (no FK — user no longer exists).')),
                ('firebase_uid_snapshot', models.CharField(help_text='Firebase UID at time of erasure.', max_length=128)),
                ('hook_failures', models.JSONField(default=list, help_text='List of hook error strings if any hooks partially failed.')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the erasure request was received.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the erasure was fully completed (set after user.delete()).', null=True)),
            ],
            options={
                'verbose_name': 'Erasure Record',
                'verbose_name_plural': 'Erasure Records',
                'ordering': ['-requested_at'],
            },
        ),
    ]
