# Generated by Django 6.0.7 on 2026-07-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ai_media_consent_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLocalePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('ui_language', models.CharField(choices=[('fr', 'French'), ('ar', 'Modern Standard Arabic'), ('en', 'English')], default='fr', max_length=8)),
                ('ui_language_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('response_language', models.CharField(blank=True, choices=[('fr', 'French'), ('ar', 'Modern Standard Arabic'), ('en', 'English')], max_length=8, null=True)),
                ('response_language_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('script_preference', models.CharField(blank=True, choices=[('latin', 'Latin'), ('arabic', 'Arabic')], max_length=8, null=True)),
                ('script_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('transliteration_preference', models.CharField(choices=[('none', 'None'), ('latin_arabic', 'Arabic in Latin script')], default='none', max_length=16)),
                ('transliteration_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('dialect', models.CharField(blank=True, choices=[('ar-MA', 'Moroccan Darija')], max_length=8, null=True)),
                ('dialect_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('glucose_unit', models.CharField(choices=[('mg/dL', 'mg/dL'), ('mmol/L', 'mmol/L')], default='mg/dL', max_length=8)),
                ('glucose_unit_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('timezone_provenance', models.CharField(choices=[('user_confirmed', 'User confirmed'), ('suggested', 'Suggested'), ('defaulted', 'Defaulted')], default='defaulted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale_preference', to='core.basepatientprofile')),
            ],
            options={
                'verbose_name': 'Patient Locale Preference',
                'verbose_name_plural': 'Patient Locale Preferences',
            },
        ),
    ]
