# Generated by Django 6.0.7 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_basepatientprofile_auth_token_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basepatientprofile",
            name="firebase_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Firebase Auth UID — temporary migration bridge.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
