# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_ai_user_throttle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientlocalepreference",
            name="dialect",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ar-MA", "Moroccan Darija"),
                    ("ar-SA", "Saudi Arabic"),
                    ("ar-AE", "Emirati Arabic"),
                    ("ar-KW", "Kuwaiti Arabic"),
                    ("ar-QA", "Qatari Arabic"),
                    ("ar-OM", "Omani Arabic"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
